[project]
name = "fin-expert-solution"
version = "0.1.0"
description = "Financial Expert Solution"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.5",
    "gunicorn>=23.0.0",
    "whitenoise>=6.9.0",
]
